spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: listing
            uri: ${LISTING_SERVICE_URL:http://localhost:8080}
            predicates:
              - Path=/api/listings/**
          - id: booking
            uri: ${BOOKING_SERVICE_URL:http://localhost:8081}
            predicates:
              - Path=/api/bookings/**
          - id: payment
            uri: ${PAYMENT_SERVICE_URL:http://localhost:8082}
            predicates:
              - Path=/api/payments/**
